Repository green-api/whatsapp-chatbot-python, pull requests merged in 2023-07, with the labels that each got.

#7 Added FSM
  README.md
  docs/README.md
  examples/echo.py
  examples/full.py
  examples/media.py
  examples/states.py
  setup.py
  whatsapp_chatbot_python/__init__.py
  whatsapp_chatbot_python/filters.py
  whatsapp_chatbot_python/manager/handler.py
  whatsapp_chatbot_python/manager/observer.py
  whatsapp_chatbot_python/manager/state.py
Labels: documentation, enhancement

#10 Updated python version
  .github/workflows/python-package.yml
  .gitignore
  requirements.txt
  setup.py
  tests/test_manager.py
  whatsapp_chatbot_python/__init__.py
  whatsapp_chatbot_python/bot.py
  whatsapp_chatbot_python/manager/handler.py
  whatsapp_chatbot_python/manager/observer.py
  whatsapp_chatbot_python/manager/router.py
Labels: enhancement, dependencies

#11 Updated version
  setup.py
Labels: dependencies

#13 added processing of all messages types
  whatsapp_chatbot_python/manager/handler.py
Labels: bug

#14 Fixed `get_message_text` method
  examples/states.py
  whatsapp_chatbot_python/filters.py
  whatsapp_chatbot_python/manager/handler.py
Labels: bug, enhancement

#15 Added parameters for the bot
  tests/test_manager.py
  whatsapp_chatbot_python/bot.py
Labels: bug, enhancement
